### ISSUE TITLE
Consider non applicable tests to be successful instead of skipped

### ISSUE THREAD

**Issue by MalteWunsch** [webfactory/symfony-application-tests#10]
When including the test suite early on in some of my projects, the first thing I usually get are skipped tests. That's no comfortable start. And when running the test suite on an older project, I cannot withstand the urge to search for the skipped tests, which in the end feels like a waste of time.

I'd like to see a "no worry dot" instead of a "scary S" in my phpunit's output.

I think that change would do no harm. I think of it as exchanging a valid statement on an empty set with another valid statement: "all Twig templates in your project are fine (maybe because there aren't any)" is just friendlier than "potential danger, we cannot say if your Twig templates are valid because there aren't any".

**Comment by Matthimatiker** [comment]
@MalteWunsch Point taken. Please check if version 0.3.0 gives you a better feeling :-)

**Comment by Matthimatiker** [comment]
Done.
