### ISSUE TITLE
testTemplateCanBeCompiled fails if no template files are available

### ISSUE THREAD

**Issue by MalteWunsch** [webfactory/symfony-application-tests#11]
When running the 0.1.1 test suite in a Symfony 2 project without any views (e.g. just console commands), testTemplateCanBeCompiled fails with:

```
1) Warning
The data provider specified for Webfactory\Tests\Integration\TwigTemplateTest::testTemplateCanBeCompiled is invalid.
You must call one of in() or append() methods before iterating over a Finder.
```

The test could skip or be considered successful (see #10) if there are no Twig templates.

**Comment by Matthimatiker** [comment]
@MalteWunsch please check if version 0.1.2 solves this issue.

**Comment by MalteWunsch** [comment]
Great success :+1:
