### ISSUE TITLE
Autoloading of annotations in data providers

### ISSUE THREAD

**Issue by MalteWunsch** [webfactory/symfony-application-tests#8]
After configuring PHPUnit to use the newly installed tests, I get failures like this:

```
1) Warning
The data provider specified for Webfactory\Tests\Integration\SecureAnnotationTest::testSecureAnnotationsReferenceExistingRoles is invalid.
[Semantical Error] The annotation "@Sensio\Bundle\FrameworkExtraBundle\Configuration\Route" in method KleineAufmerksamkeiten\WebsiteBundle\Controller\StartseiteController::startseiteAction() does not exist, or could not be auto-loaded.
```

Same with the autoloading of the `@Doctrine\ORM\Mapping\Entity` annotation.

**Comment by mpdude** [comment]
Where does the bootstrap.php.cache come from?

**Comment by MalteWunsch** [comment]
@mpdude In vanilla Symfony, the generated [bootstrap.php.cache contains definitions of many core classes](http://symfony.com/doc/current/book/performance.html#use-bootstrap-files) to reduce disc I/O and therefore increase performance. Here, it is used slightly different for bootstrapping the loading of required classes.
